name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHubリポジトリのソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. cloudflared (CLIツール)をランナーにインストール
      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
      
      # 3. Cloudflare Tunnel経由でラズパイにSSH接続し、デプロイコマンドを実行
      - name: Deploy via Cloudflare Tunnel
        env:
          # ここでGitHubの金庫から秘密の情報を読み込む
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # SSHキーを一時ファイルに書き出す
          echo "$SSH_PRIVATE_KEY" > id_deploy.pem
          chmod 600 id_deploy.pem
          
          # TCPトンネルをバックグラウンドで起動
          cloudflared access tcp \
            --hostname ssh.reiji-tanaka.com \
            --url localhost:2222 \
            --service-token-id "$CF_CLIENT_ID" \
            --service-token-secret "$CF_CLIENT_SECRET" &
          sleep 3 # トンネルが起動するのを少し待つ

          # ローカルポート経由でSSH接続し、ラズパイ上でコマンド実行
          ssh -p 2222 -o StrictHostKeyChecking=no -i ./id_deploy.pem reiji@localhost '
            set -e
            echo "--- Connected to Raspberry Pi ---"
            cd ~/portfolio-docker/web
            git pull
            docker compose up -d --build
            docker image prune -a -f
            echo "--- Deployment finished successfully! ---"
          '