name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
      
      - name: Deploy via Cloudflare Tunnel
        env:
          TUNNEL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # SSHの準備
          mkdir -p ~/.ssh
          echo "$TUNNEL_SSH_KEY" > ~/.ssh/id_deploy
          chmod 600 ~/.ssh/id_deploy
          
          # SSH設定ファイルを作成し、トンネル経由で接続するよう指示
          echo "Host ssh.reiji-tanaka.com" > ~/.ssh/config
          echo "  ProxyCommand cloudflared access ssh --hostname %h" >> ~/.ssh/config

          # 通常のSSHコマンドで、デプロイコマンドを実行
          # -i で使用する秘密鍵ファイルを指定する
          ssh -i ~/.ssh/id_deploy reiji@ssh.reiji-tanaka.com '
            set -e
            echo "--- Connected to Raspberry Pi ---"
            cd ~/portfolio-docker
            echo "--- Pulling latest code ---"
            git pull
            echo "--- Building and restarting containers ---"
            docker compose up -d --build
            echo "--- Pruning old images ---"
            docker image prune -a -f
            echo "--- Deployment finished successfully! ---"
          '