name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. cloudflaredをインストール
      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
      
      # 3. トンネル経由でデプロイコマンドを実行
      - name: Deploy via Cloudflare Tunnel
        env:
          TUNNEL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # 秘密鍵をファイルに書き出す
          echo "$TUNNEL_SSH_KEY" > key.pem
          chmod 600 key.pem

          # cloudflared access を使ってSSHコマンドを実行
          cloudflared access ssh --hostname ssh.reiji-tanaka.com --id-file ./key.pem '
            echo "--- Connected to Raspberry Pi ---"
            cd ~/portfolio-docker
            git pull
            echo "--- Building and restarting containers ---"
            docker compose up -d --build
            docker image prune -f
            echo "--- Deployment finished ---"
          '